namespace DataHubClient

open Fable.Core
open Thoth.Json.Core

/// <summary>
/// A comment on an issue or merge request. <c>System</c> notes are generated by
/// GitLab itself (e.g. "changed the status to closed"). See the
/// <see href="https://docs.gitlab.com/ee/api/notes.html">GitLab Notes API</see>.
/// </summary>
/// <param name="id">The note's unique, instance-wide numeric identifier.</param>
/// <param name="body">The note's text content.</param>
/// <param name="author">The user who created the note.</param>
/// <param name="isSystem">Whether the note was generated by GitLab rather than a user.</param>
/// <param name="createdAt">The creation timestamp as an ISO 8601 string.</param>
/// <param name="updatedAt">The last-update timestamp as an ISO 8601 string.</param>
[<AttachMembers>]
type Note(id: int, body: string, author: User, isSystem: bool, createdAt: string, updatedAt: string) =
    let mutable _id = id
    let mutable _body = body
    let mutable _author = author
    let mutable _isSystem = isSystem
    let mutable _createdAt = createdAt
    let mutable _updatedAt = updatedAt

    /// The note's unique, instance-wide numeric identifier.
    member _.Id with get () = _id and set value = _id <- value
    /// The note's text content.
    member _.Body with get () = _body and set value = _body <- value
    /// The user who created the note.
    member _.Author with get () = _author and set value = _author <- value
    /// Whether the note was generated by GitLab rather than a user.
    member _.System with get () = _isSystem and set value = _isSystem <- value
    /// The creation timestamp as an ISO 8601 string.
    member _.CreatedAt with get () = _createdAt and set value = _createdAt <- value
    /// The last-update timestamp as an ISO 8601 string.
    member _.UpdatedAt with get () = _updatedAt and set value = _updatedAt <- value

    /// Decodes a <see cref="T:DataHubClient.Note"/> from its GitLab JSON representation.
    static member Decoder : Decoder<Note> =
        Decode.object (fun get ->
            Note(
                get.Required.Field "id" Decode.int,
                get.Required.Field "body" Decode.string,
                get.Required.Field "author" User.Decoder,
                get.Required.Field "system" Decode.bool,
                get.Required.Field "created_at" Decode.string,
                get.Required.Field "updated_at" Decode.string))

    /// <summary>Encodes a <see cref="T:DataHubClient.Note"/> to its GitLab JSON representation.</summary>
    /// <param name="note">The note to encode.</param>
    static member Encoder(note: Note) : IEncodable =
        Encode.object [
            "id", Encode.int note.Id
            "body", Encode.string note.Body
            "author", User.Encoder note.Author
            "system", Encode.bool note.System
            "created_at", Encode.string note.CreatedAt
            "updated_at", Encode.string note.UpdatedAt ]
