namespace DataHubClient

open Fable.Core
open Thoth.Json.Core

/// <summary>
/// A comment on an issue or merge request. <c>System</c> notes are generated by
/// GitLab itself (e.g. "changed the status to closed"). See the
/// <see href="https://docs.gitlab.com/ee/api/notes.html">GitLab Notes API</see>.
/// </summary>
/// <param name="id">The note's unique, instance-wide numeric identifier.</param>
/// <param name="body">The note's text content.</param>
/// <param name="author">The user who created the note.</param>
/// <param name="isSystem">Whether the note was generated by GitLab rather than a user.</param>
/// <param name="createdAt">The creation timestamp as an ISO 8601 string.</param>
/// <param name="updatedAt">The last-update timestamp as an ISO 8601 string.</param>
[<AttachMembers>]
type Note(id: int, body: string, author: User, isSystem: bool, createdAt: string, updatedAt: string) =
    /// The note's unique, instance-wide numeric identifier.
    member val Id = id with get, set
    /// The note's text content.
    member val Body = body with get, set
    /// The user who created the note.
    member val Author = author with get, set
    /// Whether the note was generated by GitLab rather than a user.
    member val System = isSystem with get, set
    /// The creation timestamp as an ISO 8601 string.
    member val CreatedAt = createdAt with get, set
    /// The last-update timestamp as an ISO 8601 string.
    member val UpdatedAt = updatedAt with get, set

    /// Decodes a <see cref="T:DataHubClient.Note"/> from its GitLab JSON representation.
    static member Decoder : Decoder<Note> =
        Decode.object (fun get ->
            Note(
                get.Required.Field "id" Decode.int,
                get.Required.Field "body" Decode.string,
                get.Required.Field "author" User.Decoder,
                get.Required.Field "system" Decode.bool,
                get.Required.Field "created_at" Decode.string,
                get.Required.Field "updated_at" Decode.string))

    /// <summary>Encodes a <see cref="T:DataHubClient.Note"/> to its GitLab JSON representation.</summary>
    /// <param name="note">The note to encode.</param>
    static member Encoder(note: Note) : IEncodable =
        Encode.object [
            "id", Encode.int note.Id
            "body", Encode.string note.Body
            "author", User.Encoder note.Author
            "system", Encode.bool note.System
            "created_at", Encode.string note.CreatedAt
            "updated_at", Encode.string note.UpdatedAt ]
